---
### VERTICAL BUTTONS (fka SCENES) ###
card_vertical_button_small_joy:
  variables:
    ulm_card_vertical_button_color: "blue"
    ulm_card_vertical_button_state: "on"
    ulm_card_vertical_button_state_entity: "none"
  show_label: false
  show_name: false
  styles:
    icon:
      - color: "rgba(var(--color-theme),0.2)"
    label:
      - justify-self: "center"
      - align-self: "center"
      - font-weight: "bolder"
      - font-size: "12px"
      - filter: "opacity(40%)"
    name:
      - margin-top: "10px"
      - justify-self: "center"
      - align-self: "center"      
      - font-weight: "bold"
      - font-size: "10px"
    img_cell:
      - background-color: "rgba(var(--color-theme),0.05)"
      - border-radius: "50%"
      - place-self: "center"
      - height: "calc(var(--widget-height) - 4px)"
      - width: "calc(var(--widget-height) - 4px)" 
      - border-style: solid
      - border-width: 2px
      - border-color: rgba(var(--color-theme),0.05)          
    grid:
      - grid-template-areas: "'i'"
    card:
      - border-radius: "var(--border-radius)"
      - box-shadow: "var(--box-shadow)"
      - padding: "10px 0"
      - backdrop-filter: var(--bg-filter)
      - background: var(--card-blur-color)       
  size: "20px"
  state:
    - operator: "template"
      value: |
        [[[
          return entity.state == variables.ulm_card_vertical_button_state;
        ]]]
      styles:
        icon:
          - color: "[[[ return `rgba(${variables.ulm_card_vertical_button_color}, 1)`; ]]]"
        img_cell:
          - background-color: "[[[ return `rgba(${variables.ulm_card_vertical_button_color}, 0.2)`; ]]]"
          - border-color: "[[[ return `rgba(${variables.ulm_card_vertical_button_color}, 0.5)`; ]]]"           
        card:
          - background: >
              [[[
                    return `radial-gradient(at center, rgba(${variables.ulm_card_vertical_button_color},0.4) 0%, rgba(var(--primary-color-plain),0) 45%) 50% 50% / 200% 200% no-repeat var(--card-blur-color)`;
              ]]]
  tap_action:
    action: "call-service"
    service: |
      [[[
        if( entity.entity_id.startsWith("input_select.") )
          return "input_select.select_option";
        if( entity.entity_id.startsWith("input_boolean.") )
          return "input_boolean.toggle";
        if( entity.entity_id.startsWith("switch.") )
          return "switch.toggle";
        if( entity.entity_id.startsWith("light.") )
          return "light.toggle";
        if( entity.entity_id.startsWith("automation.") )
          return "automation.toggle";
        if( entity.entity_id.startsWith("input_button.") )
          return "input_button.press";
        if( entity.entity_id.startsWith("script.") )
          return "script.turn_on";          
        // If we need to support other entities we can add these options here.
        return "";
      ]]]
    service_data: |
      [[[
        var obj;
        if( entity.entity_id.startsWith("input_select.") )
          obj = { entity_id: entity.entity_id , option: variables.ulm_card_vertical_button_state};
        else
          obj = { entity_id: entity.entity_id};
        return obj;
      ]]]
  style:
    .: |
      ha-card #name {
        white-space: normal; 
      }