---
### VERTICAL BUTTONS (fka SCENES) ###
card_vertical_button_joy:
  variables:
    ulm_card_vertical_button_color: "blue"
    ulm_card_vertical_button_state: "on"
    ulm_card_vertical_button_state_entity: "none"
  show_label: true
  label: ""
  name: |
    [[[
      if( entity.entity_id.startsWith("input_select.") )
        return variables.ulm_card_vertical_button_state;
      else if( entity.entity_id.startsWith("input_boolean.") )
        return "";
      return entity.state;
    ]]]
  styles:
    icon:
      - color: "rgba(var(--color-theme),0.2)"
    label:
      - justify-self: "center"
      - align-self: "center"
      - font-weight: "bolder"
      - font-size: "12px"
      - filter: "opacity(40%)"
    name:
      - margin-top: "10px"
      - justify-self: "center"
      - align-self: "center"      
      - font-weight: "bold"
      - font-size: "10px"
    img_cell:
      - background-color: "rgba(var(--color-theme),0.05)"
      - border-radius: "50%"
      - place-self: "center"
      - width: "42px"
      - height: "42px"
    grid:
      - grid-template-areas: "'i' 'n' 'l'"
    card:
      - border-radius: "var(--border-radius)"
      - box-shadow: "var(--box-shadow)"
      - padding: "10px 0px 8px 0px"
      - height: "100px"
  size: "20px"
  state:
    - operator: "template"
      value: |
        [[[
          return entity.state == variables.ulm_card_vertical_button_state;
        ]]]
      styles:
        icon:
          - color: "[[[ return `rgba(var(--color-${variables.ulm_card_vertical_button_color}), 1)`; ]]]"
        label:
          - color: "[[[ return `rgba(var(--color-${variables.ulm_card_vertical_button_color}-text), 1)`; ]]]"
        name:
          - color: "[[[ return `rgba(var(--color-${variables.ulm_card_vertical_button_color}-text), 1)`; ]]]"
        img_cell:
          - background-color: "[[[ return `rgba(var(--color-${variables.ulm_card_vertical_button_color}), 0.2)`; ]]]"
        card:
          - background-color: "[[[ return `rgba(var(--color-background-${variables.ulm_card_vertical_button_color}), var(--opacity-bg))`; ]]]"
  tap_action:
    action: "call-service"
    service: |
      [[[
        if( entity.entity_id.startsWith("input_select.") )
          return "script.turn_on";
        if( entity.entity_id.startsWith("input_boolean.") )
          return "input_boolean.toggle";
        if( entity.entity_id.startsWith("switch.") )
          return "switch.toggle";
        if( entity.entity_id.startsWith("light.") )
          return "light.toggle";
        if( entity.entity_id.startsWith("automation.") )
          return "automation.toggle";
        if( entity.entity_id.startsWith("input_button.") )
          return "input_button.press";
        if( entity.entity_id.startsWith("script.") )
          return "script.turn_on";          
        // If we need to support other entities we can add these options here.
        return "";
      ]]]
    service_data: |
      [[[
        var obj;
        if( entity.entity_id.startsWith("input_select.") )
          obj = { entity_id: variables.ulm_card_vertical_button_state_entity};
        else
          obj = { entity_id: variables.ulm_card_vertical_button_state_entity , option: variables.ulm_card_vertical_button_state  };
        return obj;
      ]]]
  style:
    .: |
      ha-card #name {
        white-space: normal; 
      }