---
### Card Light ###
card_light_joy_tree_lights:
  template:
    - "icon_more_info_new"
    - "ulm_translation_engine"
  variables:
    ulm_card_light_name: "[[[ return entity.attributes.friendly_name ]]]"
    ulm_card_light_icon: "[[[ return entity.attributes.icon ]]]"
    ulm_card_light_enable_collapse: false
    ulm_card_light_enable_slider: false
    ulm_card_light_enable_slider_minSet: 0
    ulm_card_light_enable_slider_maxSet: 100
    ulm_card_light_enable_horizontal: false
    ulm_card_light_enable_horizontal_wide: false
    ulm_card_light_enable_color: false
    ulm_card_light_force_background_color: false
    ulm_card_light_enable_popup: false
    ulm_card_light_enable_popup_tap: false
    ulm_card_light_color: "var(--color-yellow)" 
    ulm_card_light_double_row_color: "var(--color-yellow)" 
    ulm_card_light_double_row: false
    ulm_card_light_double_row_entity: "[[[ return entity.entity_id ]]]"
  show_icon: false
  show_name: false
  show_label: false
  state:
    - value: "on"
      styles:
        card:
          - background-color: >-
              [[[
                  var color = variables.ulm_card_light_color;
                  return 'rgba(' + color + ',0.1)';
              ]]]
  styles:
    grid:
      - grid-template-areas: >
          [[[
                if (variables.ulm_card_light_enable_collapse && entity.state != "on") {
                    return "\"item1\"";
                } else if (variables.ulm_card_light_enable_horizontal) {
                    return "\"item1 item2\"";
                } else if (variables.ulm_card_light_enable_slider && !variables.ulm_card_light_double_row) {
                    return "\"item1\" \"item2\"";
                } else if (variables.ulm_card_light_enable_slider && variables.ulm_card_light_double_row) {
                    return "\"item1\" \"item2\" \"item3\"";                    
                } else {
                    return "\"item1\"";
                }
          ]]]
      - grid-template-columns: >
          [[[
                if (variables.ulm_card_light_enable_collapse && entity.state != "on") {
                    return "1fr";
                } else if (variables.ulm_card_light_enable_horizontal) {
                  if(variables.ulm_card_light_enable_horizontal_wide){
                    return "1fr 2fr";
                    } else {
                      return "1fr 1fr";
                    }
                } else {
                    return "1fr";
                }
          ]]]
      - grid-template-rows: >
          [[[
                if (variables.ulm_card_light_enable_collapse && entity.state != "on") {
                    return "1fr";
                } else if (variables.ulm_card_light_enable_slider && !variables.ulm_card_light_enable_horizontal && !variables.ulm_card_light_double_row) {
                    return "min-content min-content";
                } else if (variables.ulm_card_light_enable_slider && !variables.ulm_card_light_enable_horizontal && variables.ulm_card_light_double_row) {
                    return "min-content min-content min-content";                    
                } else {
                    return "1fr";
                }
          ]]]
      - row-gap: "12px"
    card:
      - border-radius: "var(--border-radius)"
      - box-shadow: "var(--box-shadow)"
      - padding: "12px"
      - backdrop-filter: var(--bg-filter)
      - background: var(--card-blur-color)          
    custom_fields:
      item2:
        - display: >
            [[[
                  if (variables.ulm_card_light_enable_collapse && entity.state != "on") {
                      return "none";
                  } else if (variables.ulm_card_light_enable_slider) {
                      return "block";
                  } else {
                      return "none";
                  }
            ]]]
      item3:
        - display: >
            [[[
                  if (variables.ulm_card_light_enable_collapse && entity.state != "on") {
                      return "none";
                  } else if (variables.ulm_card_light_enable_slider && variables.ulm_card_light_double_row) {
                      return "block";
                  } else {
                      return "none";
                  }
            ]]]            
  custom_fields:
    item1:
      card:
        type: "custom:button-card"
        custom_fields:
          item1:
            card:
              type: "custom:button-card"
              entity: "[[[ return entity.entity_id ]]]"
              icon: "[[[ return variables.ulm_card_light_icon ]]]"
              variables: >
                [[[
                  let vars = variables;
                  if(variables.ulm_card_light_enable_popup) {
                    vars.ulm_custom_popup = {
                      'template': 'popup_light_brightness'
                    };
                  }
                  return vars;
                ]]]
              styles:
                card:
                  - background-color: transparent              
                icon:
                  - color: >
                      [[[
                          var color = variables.ulm_card_light_color;
                          if (entity.state != "on"){
                            return 'rgba(var(--color-theme),0.2)';
                          }
                          else{
                            return 'rgba(' + color + ', 1)';
                          }
                      ]]]
                img_cell:
                  - background-color: >
                      [[[
                          var color = variables.ulm_card_light_color;
                          if (entity.state != "on"){
                            return 'rgba(var(--color-theme),0.05)';
                          }
                          else{
                            return 'rgba(' + color + ', 0.2)';
                          }
                      ]]]
          item2:
            card:
              type: "custom:button-card"
              entity: "[[[ return entity.entity_id ]]]"
              variables: >
                [[[
                  let vars = variables;
                  if(variables.ulm_card_light_enable_popup) {
                    vars.ulm_custom_popup = {
                      'template': 'popup_light_brightness'
                    };
                  }
                  return vars;
                ]]]
              name: "[[[ return variables.ulm_card_light_name ]]]"
              label: >-
                [[[
                  var label = variables.ulm_translation_state
                    if (entity.attributes.brightness != null && entity.state === 'on'){
                      var bri = Math.round(entity.attributes.brightness / 2.55);
                      var label = (bri ? bri : "0") + "%";
                    }
                  return label;
                ]]]
              state:
                - value: "on"
                  styles:
                    name:
                      - color: >-
                          [[[
                            var color = variables.ulm_card_light_color;
                            return 'rgba(' + color + ', 1)';
                          ]]]
                    label:
                      - color: >-
                          [[[
                            var color = variables.ulm_card_light_color;
                            return 'rgba(' + color + ', 1)';
                          ]]]
    item2:
      card:
        type: "custom:my-slider"
        entity: "[[[ return entity.entity_id ]]]"
        radius: "14px"
        height: "42px"
        minSet: "[[[ return variables.ulm_card_light_enable_slider_minSet ]]]"
        maxSet: "[[[ return variables.ulm_card_light_enable_slider_maxSet ]]]"
        mainSliderColor: >
          [[[
              var color = variables.ulm_card_light_color;
              if (entity.state == "unavailable"){
                return "rgba(var(--color-theme),0.05)";
              }
              else{
                return 'rgba(' + color + ', 1)';
              }
          ]]]
        secondarySliderColor: >
          [[[
              var color = variables.ulm_card_light_color;
              if (entity.state == "unavailable"){
                return "rgba(var(--color-theme),0.05)";
              }
              else{
                return 'rgba(' + color + ', 0.2)';
              }
          ]]]
        thumbColor: >
          [[[
              var color = variables.ulm_card_light_color;
              if (entity.state == "unavailable"){
                return "rgba(var(--color-theme),0.05)";
              }
              else{
                return 'rgba(' + color + ', 1)';
              }
          ]]]
        mainSliderColorOff: "rgba(var(--color-theme),0.05)"
        secondarySliderColorOff: "rgba(var(--color-theme),0.05)"
        thumbColorOff: "rgba(var(--color-theme),0)"
        thumbHorizontalPadding: "0px"
        thumbVerticalPadding: "0px"
        thumbWidth: "12px"
        card_mod:
        style: |
          ha-card {
            border-radius: 14px;
            box-shadow: none;
            background-color: transparent;           
          }
    item3:
      card:
        type: "custom:my-slider"
        entity: "[[[ return variables.ulm_card_light_double_row_entity ]]]"
        radius: "14px"
        height: "42px"
        minSet: "[[[ return variables.ulm_card_light_enable_slider_minSet ]]]"
        maxSet: "[[[ return variables.ulm_card_light_enable_slider_maxSet ]]]"
        mainSliderColor: >
          [[[
              var color = variables.ulm_card_light_double_row_color;
              if (entity.state == "unavailable"){
                return "rgba(var(--color-theme),0.05)";
              }
              else{
                return 'rgba(' + color + ', 1)';
              }
          ]]]
        secondarySliderColor: >
          [[[
              var color = variables.ulm_card_light_double_row_color;
              if (entity.state == "unavailable"){
                return "rgba(var(--color-theme),0.05)";
              }
              else{
                return 'rgba(' + color + ', 0.2)';
              }
          ]]]
        thumbColor: >
          [[[
              var color = variables.ulm_card_light_double_row_color;
              if (entity.state == "unavailable"){
                return "rgba(var(--color-theme),0.05)";
              }
              else{
                return 'rgba(' + color + ', 1)';
              }
          ]]]
        mainSliderColorOff: "rgba(var(--color-theme),0.05)"
        secondarySliderColorOff: "rgba(var(--color-theme),0.05)"
        thumbColorOff: "rgba(var(--color-theme),0)"
        thumbHorizontalPadding: "0px"
        thumbVerticalPadding: "0px"
        thumbWidth: "12px"
        card_mod:
        style: |
          ha-card {
            border-radius: 14px;
            box-shadow: none;
            background-color: transparent;         
          }