---
### Chips ###
chips_blank:
  show_icon: false
  show_label: false
  show_name: false
  show_state: false
  styles:
    card:
      - height: "36px"
      - box-shadow: "none"
      - background: "transparent"
  size: "80%"
