---
### Icon More Info ###
icon_more_info_group:
  show_icon: false
  show_name: false
  show_label: false
  styles:
    grid:
      - grid-template-columns: "min-content"
      - column-gap: "0px"
    card:
      - background-color: "rgba(0,0,0,0)"
      - box-shadow: "none"
      - padding: "0px"         
  hold_action:
    action: "more-info"
  custom_fields:
    item1:
      card:
        type: "custom:button-card"
        entity: "[[[ return entity.entity_id ]]]"
        template:
          - "icon"
        styles:
          card:
            - overflow: "visible"
        tap_action:
          action: "more-info"
