---
### Icon More Info ###
icon_more_info_wled:
  show_icon: false
  show_name: false
  show_label: false
  styles:
    grid:
      - grid-template-areas: "'item1 item2 item3'"    
      - grid-template-columns: "min-content auto min-content"     
      - column-gap: "0px"
    card:
      - background-color: "rgba(0,0,0,0)"
      - box-shadow: "none"
      - padding: "0px"
      - border-radius: "0"      
  hold_action:
    action: "more-info"
  custom_fields:
    item1:
      card:
        type: "custom:button-card"
        entity: "[[[ return entity.entity_id ]]]"
        template:
          - "icon"
        styles:
          card:
            - overflow: "visible"
        tap_action:
          action: "more-info"
    item2:
      card:
        type: "custom:button-card"
        show_icon: false
        entity: "[[[ return entity.entity_id ]]]"
        template:
          - "icon_info"
        styles:
          card:
            - padding: "6px"
            - margin-left: "-6px"
            - background-color: "rgba(0,0,0,0)"
        custom_fields:
