---
### Icon Info ###
icon_info_motion_graph:
  color: "var(--google-grey)"
  show_icon: true
  show_label: true
  show_name: true
  state:
    - styles:
        custom_fields:
          notification:
            - border-radius: "50%"
            - position: "absolute"
            - left: "38px"
            - top: "8px"
            - height: "12px"
            - width: "12px"
            - border: "2px solid var(--card-background-color)"
            - font-size: "8px"
            - line-height: "10px"
            - background-color: >
                [[[
                  return "rgba(var(--color-red),1)";
                ]]]
      value: "unavailable"
  style:
    .: |
      ha-card #notification ha-icon {
        width: 10px !important;
        height: 10px !important;
      }    
  styles:
    icon:
      - color: "rgba(var(--color-theme),0.2)"
    label:
      - justify-self: "start"
      - align-self: "start"
      - font-weight: "bolder"
      - font-size: "12px"
      - filter: "opacity(40%)"
      - margin-left: "12px"
    name:
      - align-self: "end"
      - justify-self: "start"
      - font-weight: "bold"
      - font-size: "14px"
      - margin-left: "12px"
    state:
      - justify-self: "start"
      - align-self: "start"
      - font-weight: "bolder"
      - font-size: "12px"
      - filter: "opacity(40%)"
      - margin-left: "12px"
    img_cell:
      - background-color: "rgba(var(--color-theme),0.05)"
      - border-radius: "50%"
      - place-self: "center"
      - width: "42px"
      - height: "42px"
    grid:
      - grid-template-areas: "'i n' 'i l'"
      - grid-template-columns: "min-content auto"
      - grid-template-rows: "min-content min-content"
    card:
      - border-radius: "21px 8px 8px 21px"
      - box-shadow: "none"
      - padding: "0px"
      # - background-color: "rgba(var(--color-theme),0)"
  custom_fields:
    notification: >
      [[[
        if (entity.state =="unavailable"){
          return `<ha-icon icon="mdi:exclamation" style="width: 10px; height: 10px; color: var(--primary-background-color);"></ha-icon>`
        }
      ]]]
  size: "20px"
